# Change these first
owner: appio-smart-kitchen # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Delivery Appio
    url: https://delivery.appio.com.mx/
  - name: Growth Appio
    url: https://growth.appio.com.mx/
  - name: Gaming Appio
    url: https://gaming.appio.com.mx/
  - name: Registro Appio
    url: https://registro.appio.com.mx
  - name: Panel Appio
    url: https://panel.appio.com.mx
  - name: Delivery Api
    url: https://deliveryapi.appio.com.mx/
    expectedStatusCodes:
      - 200
      - 404
  - name: Payment Api
    url: https://paymentapi.appio.com.mx/api
    expectedStatusCodes:
      - 200
      - 404
  - name: Appio Api
    url: https://api.appio.com.mx/api/v2/upptime/validate
    expectedStatusCodes:
      - 200
      - 404
  - name: Staging Panel Apio
    url: https://stagingpanel.appio.com.mx
  - name: Staging Appio Api
    url: https://stagingapi.appio.com.mx/api/v2/upptime/validate 
    expectedStatusCodes:
      - 200
      - 404
assignees:
  - Esaud17
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.esaudrivera.com
  baseUrl: /upptime
  logoUrl: https://panel.appio.com.mx/icon.ico
  name: Appio Status
  introTitle: "**Apio** Monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page showing data in **real time** from our services [Appio](https://www.appio.com.mx).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
